/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-04-09 06:52:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class Admin_005fInspectionView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/inc/admin_topbar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_funding/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_funding/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Puding</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("  ");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Puding</title>\n");
      out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\n");
      out.write("<!--  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script> -->\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("#ho:hover {\n");
      out.write("\tposition: relative;\n");
      out.write("\ttop: calc(100% - 0.125rem);\n");
      out.write("\tborder-bottom: 4px solid #FFA7A7;\n");
      out.write("\tleft: 50%;\n");
      out.write("\tright: 50%;\n");
      out.write("\ttransition: all 0.5s ease;\n");
      out.write(" \tleft: 0;\n");
      out.write("  \tright: 0;\n");
      out.write(" \ttransition: all 0.5s ease;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<nav\n");
      out.write("\t\tclass=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\n");
      out.write("\t\tid=\"sectionsNav\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"navbar-translate\">\n");
      out.write("\t\t\t\t<a href=\"main.do\"><img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:100px;\"/></a>\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\" >\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\">\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\n");
      out.write("                    <a href=\"project_list.do?page=1\" class=\"nav-link\">프로젝트 찾기</a>\n");
      out.write("                  </li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\">\n");
      out.write("\t\t\t\t\t\t<a href=\"message_re.do?page=1\" class=\"btn btn-rose btn-raised btn-fab btn-round\">\n");
      out.write("\t\t\t\t\t\t\t <i class=\"material-icons\">email</i>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\n");
      out.write("\t\t\t\t\t\t<a href=\"logOut.do\" class=\"nav-link\"style=\"color: white\">Log out</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<nav\n");
      out.write("\t\tclass=\"navbar navbar-transparent fixed-top navbar-expand-lg\"\n");
      out.write("\t\tid=\"sectionsNav2\"\n");
      out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"navbar-translate\" style=\"width: 100px;\">\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\t\taria-expanded=\"false\" data-target=\"#investor_topbar\">\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"investor_topbar\">\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav\" style=\"color:black;\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"admin_coin.do\" class=\"nav-link\" id=\"ho\"\n");
      out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">환불 신청 내역</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"admin_inspectionList.do\" class=\"nav-link\" id=\"ho\"\n");
      out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">프로젝트 신청 내역</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"admin_typeupdate.do\" class=\"nav-link\" id=\"ho\"\n");
      out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">계정 유형 신청</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\n");
      out.write("\t</nav>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"resources/assets/css/project_view.css\" rel=\"stylesheet\" />\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\"\n");
      out.write("\thref=\"resources/assets/img/apple-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\"\n");
      out.write("\thref=\"resources/assets/img/favicon.png\">\n");
      out.write("\n");
      out.write("<!--     Fonts and icons     -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write("<!-- CSS Files -->\n");
      out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- CSS Just for demo purpose, don't include it in your project -->\n");
      out.write("<link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\n");
      out.write("\t// 제이쿼리 시작!\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$(\"#chkbt\").click(function(){\n");
      out.write("\t\t\talert(\"승인 처리 되었습니다.\");\n");
      out.write("\t\t})\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#chkbt2\").click(function(){\n");
      out.write("\t\t\talert(\"폐기 처리 되었습니다.\");\n");
      out.write("\t\t})\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      com.klp.pf.dto.PF_BoardDto dto = null;
      dto = (com.klp.pf.dto.PF_BoardDto) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new com.klp.pf.dto.PF_BoardDto();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      out.write('	');
      com.klp.pf.dto.PF_CommentDto comment_dto = null;
      comment_dto = (com.klp.pf.dto.PF_CommentDto) _jspx_page_context.getAttribute("comment_dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (comment_dto == null){
        comment_dto = new com.klp.pf.dto.PF_CommentDto();
        _jspx_page_context.setAttribute("comment_dto", comment_dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("\t<div class=\"main main-raised\">\n");
      out.write("\t\t<div class=\"project_view_container\">\n");
      out.write("\t\t\t<div class=\"row\" id=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-9\" id=\"col10\">\n");
      out.write("\t\t\t\t\t<div class=\"view_title\">\n");
      out.write("\t\t\t\t\t\t<h3>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"tim-note\"><b>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.klp.pf.dto.PF_BoardDto)_jspx_page_context.findAttribute("dto")).getBoard_title())));
      out.write("</b></span>\n");
      out.write("\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"resources/assets/img/heart.PNG\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 20px;\" />&nbsp;&nbsp;<b>관심 프로젝트</b></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"view_title2\">\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">개발 >");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.klp.pf.dto.PF_BoardDto)_jspx_page_context.findAttribute("dto")).getProject_category())));
      out.write("</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\" id=\"support\">총 0명 지원</p>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t");

							String a = dto.getBoard_regdate();
							System.out.println(a);
							Date Ato = new SimpleDateFormat("yyyy-MM-dd").parse(a);
							System.out.println(Ato);

							String b = dto.getRecruit_date();
							System.out.println(b);
							Date Bto = new SimpleDateFormat("yyyy-MM-dd").parse(b);
							System.out.println(Bto);

							long diffSec = Bto.getTime() - Ato.getTime();
							long diffDays = diffSec / (24 * 60 * 60 * 1000);
							System.out.println(diffDays);

							dto.setRecruit(diffDays);
						
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<span class=\"badge badge-pill badge-success\">마감 ");
      out.print(dto.getRecruit());
      out.write("일 전</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"view_title_detail\">\n");
      out.write("\t\t\t\t\t\t<div class=\"project_title2\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project_money\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/assets/img/money.png\" />&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>예상 금액</b>&nbsp;&nbsp;&nbsp;<b>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.klp.pf.dto.PF_BoardDto)_jspx_page_context.findAttribute("dto")).getProject_money())));
      out.write("원</b>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>등록일</b>&nbsp;&nbsp;&nbsp;<b> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.board_regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </b>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project_time\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/assets/img/time.png\" />&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>예상 시간</b>&nbsp;&nbsp;&nbsp;<b>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.klp.pf.dto.PF_BoardDto)_jspx_page_context.findAttribute("dto")).getProject_term())));
      out.write("일</b>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>예상 시작일</b>&nbsp;&nbsp;&nbsp;<b>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.klp.pf.dto.PF_BoardDto)_jspx_page_context.findAttribute("dto")).getProject_start_day())));
      out.write("</b>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"project_support\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/assets/img/K-021.png\" />&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>모집 마감</b>&nbsp;&nbsp;&nbsp;<b>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.klp.pf.dto.PF_BoardDto)_jspx_page_context.findAttribute("dto")).getRecruit_date())));
      out.write("</b>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t<br />\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<hr />\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"project_content\">\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\" id=\"detail\">\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");

								dto.setBoard_content(dto.getBoard_content().replace("\r\n", "<br>"));
								dto.setBoard_content(dto.getBoard_content().replace("\u0020", " "));
							
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(dto.getBoard_content() );
      out.write("\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-3\" id=\"col2\">\n");
      out.write("\t\t\t\t\t<div class=\"client_container\">\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t<b>클라이언트</b>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"client_img\">\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/examples/studio-5.jpg\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"rounded-circle img-fluid\" />\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">클라이언트에 대한 소개 어쩌구 저쩌구 어쩌구 저쩌구!!!\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"star\">\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">별점 공간</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"project_area\">\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t<b>프로젝트 등록</b>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\" id=\"p\">1건</p>\n");
      out.write("\t\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t<b>등록한 프로젝트</b>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\" id=\"p2\">1건</p>\n");
      out.write("\t\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t<b>완료한 프로젝트</b>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\" id=\"p2\">1건</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"total_money\">\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">\n");
      out.write("\t\t\t\t\t\t\t<b>누적 완료 금액</b>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"money\">\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">0원</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<hr/>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"file_upload\">\n");
      out.write("\t\t\t\t<!-- \t\t<iframe src=\"http://docs.google.com/gview?url=http://localhost:8787/pf/storage/test.pdf&embedded=true\" style=\"width:100%; height:500px;\" frameborder=\"0\"></iframe> -->\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<div id=\"comment_container2\">\n");
      out.write("\t\t\t<div id=\"comment_list\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\"href=\"resources/assets/img/apple-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"resources/assets/img/favicon.png\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("<title>Material Kit by Creative Tim</title>\n");
      out.write("<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\n");
      out.write("<!-- Fonts and icons -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write("<!-- CSS Files -->\n");
      out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- CSS Just for demo purpose, don't include it in your project -->\n");
      out.write("<link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- fontawesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<footer class=\"footer\" data-background-color=\"black\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<nav class=\"float-left\">\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"text-align: left;\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t<h3><strong>About the Page</strong></h3>\n");
      out.write("\t\t\t\t\t\t<p>How much of a dream do you have in pudding You can realize your dreams. We will create opportunities. Challenge yourself. I support your high dream.</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t<h3><strong>Macker.</strong></h3>\n");
      out.write("\t\t\t\t\t\t<p> Team. 김이박 </p>\n");
      out.write("\t\t\t\t\t\t<p> With. 2019. 02. 08</p>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:250px;\"/>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Admin_InspectionView.jsp(188,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.board_file ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<iframe src=\"http://localhost:8787/pf/storage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.board_file }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\n");
          out.write("\t\t\t\t\t\tstyle=\"width: 100%; height: 500px;\" frameborder=\"0\"></iframe>\n");
          out.write("\t\t\t\t\t");
          out.write("\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /Admin_InspectionView.jsp(195,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '투자자' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t<div class=\"button_container\" style=\"text-align: center;\">\n");
          out.write("\t\t\t\t\t<button class=\"btn btn-info btn-lg\"\n");
          out.write("\t\t\t\t\t\tstyle=\"display: inline-block; width: 150px;\">투자하기</button>\n");
          out.write("\t\t\t\t</div>\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /Admin_InspectionView.jsp(202,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '파트너스' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t<div class=\"partners_button\">\n");
          out.write("\t\t\t\t\t<button id=\"partners\" class=\"btn btn-rose btn-lg\"\n");
          out.write("\t\t\t\t\t\tstyle=\"display: inline-block; width: 150px;\">지원하기</button>\n");
          out.write("\t\t\t\t</div>\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /Admin_InspectionView.jsp(212,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '관리자' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <div class=\"button_container\" style=\"text-align: center;\">\n");
          out.write("           <button class=\"btn btn-info btn-lg\" id=\"chkbt\" style=\"display: inline-block; width: 150px;\"\n");
          out.write("            onclick=\"location.href='admin_changeproject.do?board_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.board_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&project_state=");
          out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.klp.pf.dto.PF_BoardDto)_jspx_page_context.findAttribute("dto")).getProject_state())));
          out.write("'\">승인하기</button>\n");
          out.write("       \t   <button class=\"btn btn-default btn-lg\" id=\"chkbt2\" style=\"display: inline-block; width: 150px;\"\n");
          out.write("       \t   onclick=\"location.href='admin_deleteproject.do?board_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.board_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&project_state=");
          out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.klp.pf.dto.PF_BoardDto)_jspx_page_context.findAttribute("dto")).getProject_state())));
          out.write("'\">폐기하기</button>\n");
          out.write("        </div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
