/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-04-09 06:39:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Project_005fInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/client_topbar.jsp", Long.valueOf(1566188445000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html;charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Puding</title>\r\n");
      out.write(" ");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Puding</title>\n");
      out.write("\n");
      out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\n");
      out.write(" <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n");
      out.write("\t<!-- 구글로그인api -->\n");
      out.write("<script src=\"https://apis.google.com/js/platform.js\" async defer></script>\n");
      out.write("<meta name=\"google-signin-scope\" content=\"profile email\">\n");
      out.write("<meta name=\"google-signin-client_id\" content=\"194507075586-fqdh9s1af0jq81cq27hqe5m9fim0692t.apps.googleusercontent.com\">\n");
      out.write("\t\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#ho:hover {\n");
      out.write("\tposition: relative;\n");
      out.write("\ttop: calc(100% - 0.125rem);\n");
      out.write("\tborder-bottom: 4px solid #FFA7A7;\n");
      out.write("\tleft: 50%;\n");
      out.write("\tright: 50%;\n");
      out.write("\ttransition: all 0.5s ease;\n");
      out.write("\tleft: 0;\n");
      out.write("\tright: 0;\n");
      out.write("\ttransition: all 0.5s ease;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("   <nav\n");
      out.write("      class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\n");
      out.write("      id=\"sectionsNav\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"navbar-translate\">\n");
      out.write("            <!-- 상단 메뉴바 -->\n");
      out.write("            <a href=\"main.do\"><img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:100px;\"/></a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("               aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("               <span class=\"sr-only\">Toggle navigation</span> \n");
      out.write("               <span class=\"navbar-toggler-icon\"></span> <span\n");
      out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
      out.write("                  class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"collapse navbar-collapse\">\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"client_mypage.do\" class=\"nav-link\">나의\n");
      out.write("\t\t\t\t\t\t\t푸딩</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\">\n");
      out.write("\t\t\t\t\t\t<a href=\"project_insert.do\" class=\"nav-link\" style=\"color: white\">프로젝트 등록</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_list.do?page=1\"\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link\" style=\"color: white\">프로젝트 찾기</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a\n");
      out.write("\t\t\t\t\t\thref=\"partner_list.do\" class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\tstyle=\"color: white\">파트너스 목록</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"question.do\" class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\tstyle=\"color: white\">이용 방법</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\">\n");
      out.write("\t\t\t\t\t<a href=\"message_re.do?page=1\" class=\"btn btn-rose btn-raised btn-fab btn-round\"> <i\n");
      out.write("\t\t\t\t\t\tclass=\"material-icons\">email</i></a> \n");
      out.write("\t\t\t\t\t<!-- <a class=\"btn btn-rose btn-raised btn-fab btn-round\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a> -->\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"logOut.do\" class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\tstyle=\"color: white\" onclick=\"signOut();\">Logout</a></li>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<nav class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\" id=\"sectionsNav\"\n");
      out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\n");
      out.write("   <nav\n");
      out.write("      class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\n");
      out.write("      id=\"sectionsNav\"\n");
      out.write("      style=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <div class=\"navbar-translate\" style=\"width: 100px;\">\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("               aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("               <span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
      out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
      out.write("                  class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("         </div>\n");
      out.write("\n");
      out.write("         <div class=\"collapse navbar-collapse\">\n");
      out.write("            <ul class=\"navbar-nav\" style=\"color:black;\">\n");
      out.write("               <li class=\"nav-item\"><a href=\"project_inspectionList.do?user_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("               class=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">검수중인 프로젝트</a></li>\n");
      out.write("               <li class=\"nav-item\"><a href=\"project_recruitmentList.do?user_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"nav-link\" id=\"ho\"\n");
      out.write("                  style=\"padding-top: 17px;\">지원자 모집 중</a></li>\n");
      out.write("                <li class=\"nav-item\"><a href=\"project_ing.do?page=1&user_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"nav-link\" id=\"ho\"\n");
      out.write("                  style=\"padding-top: 17px;\">진행중인 프로젝트</a></li>\n");
      out.write("                  <li class=\"nav-item\"><a href=\"project_end.do?page=1&user_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"nav-link\" id=\"ho\"\n");
      out.write("                  style=\"padding-top: 17px;\">완료한 프로젝트</a></li>\n");
      out.write("                  <li class=\"nav-item\"><a href=\"user_typeUpdate.do\" class=\"nav-link\" id=\"ho\"\n");
      out.write("                  style=\"padding-top: 17px;\">계정 유형 변경 신청</a></li>\n");
      out.write("            </ul>\n");
      out.write("         </div>\n");
      out.write("         </div>\n");
      out.write("         </nav>\n");
      out.write("         \n");
      out.write("   </nav>\n");
      out.write("   <br><br><br>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  function signOut() {\n");
      out.write("    var auth2 = gapi.auth2.getAuthInstance();\n");
      out.write("    auth2.signOut().then(function () {\n");
      out.write("      console.log('User signed out.');\n");
      out.write("    });\n");
      out.write("  }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<link href=\"resources/assets/css/project_insert.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"resources/assets/img/apple-icon.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"resources/assets/img/favicon.png\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t<title>\r\n");
      out.write(" \t Puding\r\n");
      out.write(" \t </title>\r\n");
      out.write(" \t<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\r\n");
      out.write("  \t<!--     Fonts and icons     -->\r\n");
      out.write("  \t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\r\n");
      out.write(" \t <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\r\n");
      out.write(" \t <!-- CSS Files -->\r\n");
      out.write(" \t <link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\r\n");
      out.write("  \t<!-- CSS Just for demo purpose, don't include it in your project -->\r\n");
      out.write("  \t<link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function CheckForm(Join){\r\n");
      out.write("\tvar project_category = document.register.project_category;\t\t//카테고리\r\n");
      out.write("\tvar board_title = document.register.board_title; \t\t\t\t//제목\r\n");
      out.write("\tvar project_money= document.register.project_money;\t//예상금액\r\n");
      out.write("\tvar project_term = document.register.project_term;\t\t//예상 기간\r\n");
      out.write("\tvar board_content = document.register.board_content;\t\t//프로젝트 내용\r\n");
      out.write("\tvar project_start_day=document.register.project_start_day;\t//프로젝트 예상시작일\r\n");
      out.write("\tvar recruit_date = document.register.recruit_date;\t\t\t\t\t//모집 마감일자\r\n");
      out.write("\tvar project_type = document.register.project_type;\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif(project_category.value==\"\"){\r\n");
      out.write("\r\n");
      out.write("\t\tproject_category.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(board_title.value==\"\"){\r\n");
      out.write("\t\tboard_title.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(project_money.value==\"\"){\r\n");
      out.write("\t\tproject_money.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(project_term.value==\"\"){\r\n");
      out.write("\t\tproject_term.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(board_content.value==\"\"){\r\n");
      out.write("\t\tboard_content.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(project_start_day.value==\"\"){\r\n");
      out.write("\t\tproject_start_day.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(recruit_date.value==\"\"){\r\n");
      out.write("\t\trecruit_date.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!project_type.checked){\r\n");
      out.write("\t\tproject_type.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main main-raised\">\r\n");
      out.write("<div class=\"insert_container\">\r\n");
      out.write("\t<div class=\"col-md-1\" id=\"col1\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-md-10\" id=\"col10\">\r\n");
      out.write("\t\t<form action=\"insert.do?user_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"post\" onclick=\"return CheckForm(this)\" name=\"register\">\r\n");
      out.write("\t\t<input type='hidden' name=\"user_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t<div class=\"container_title\">\r\n");
      out.write("\t\t<h3><span class=\"tim-note\"><b>프로젝트 등록</b></span></h3>\r\n");
      out.write(" \t\t<div class=\"project_insert\">\r\n");
      out.write(" \t\t\t<img src=\"resources/assets/img/K-023.png\" style=\"width: 50px;\"/> \r\n");
      out.write(" \t\t</div> \r\n");
      out.write("\t\t\t<p class=\"text-muted\" style=\"font-size: 13px;\">\r\n");
      out.write("\t\t\t진행하고 싶은 프로젝트를 등록해주세요.\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container_content\">\r\n");
      out.write("\t\t\t<div class=\"project_content\">\r\n");
      out.write("\t\t\t\t<div class=\"project_title\">\r\n");
      out.write("\t\t\t\t\t<h5><b>프로젝트 제목</b></h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"select_category\">\r\n");
      out.write("\t\t\t\t\t<select name=\"project_category\" style=\"font-size: 13px;\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected>카테고리</option>\r\n");
      out.write("  \t\t\t\t\t\t<option value=\"웹\">웹</option>\r\n");
      out.write("  \t\t\t\t\t\t<option value=\"어플리케이션\">어플리케이션</option>\r\n");
      out.write("  \t\t\t\t\t\t<option value=\"일반 소프트웨어\">일반 소프트웨어</option>\r\n");
      out.write("  \t\t\t\t\t\t<option value=\"게임\">게임</option>\r\n");
      out.write("  \t\t\t\t\t\t<option value=\"임베디드\">임베디드</option>\r\n");
      out.write("  \t\t\t\t\t\t<option value=\"퍼블리싱\">퍼블리싱</option>\r\n");
      out.write("  \t\t\t\t\t\t<option value=\"기타\">기타</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group has-default\" id=\"form_subject\">\r\n");
      out.write("            \t   \t<input type=\"text\" class=\"form-control\" placeholder=\"제목을 입력해주세요.\" name=\"board_title\">\r\n");
      out.write("          \t\t</div>\r\n");
      out.write("            \r\n");
      out.write("           \t\t<div class=\"money_container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"money\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/money.png\" style=\"width: 20px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"money_input\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">예상금액</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" id=\"form2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"control\" name=\"project_money\" placeholder=\"1,000,000\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-muted\" id=\"won\">원</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"time_container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/time.png\" style=\"width: 20px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"time_input\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">예상기간</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\" id=\"form2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"control\" name=\"project_term\" placeholder=\"30\" >\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-muted\" id=\"day\">일</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_content2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t<h5><b>프로젝트 내용</b></h5>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<pre>\r\n");
      out.write("\t\t\t\t\t<textarea rows=\"15\" cols=\"121\" name=\"board_content\"></textarea></pre>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"file_content\">\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"board_file\" name=\"board_file\" hidden=\"\" />\r\n");
      out.write("\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"start_container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"start_input\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">프로젝트 예상 시작일</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"start_select\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"control\" name=\"project_start_day\" placeholder=\"2019-02-01\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-muted\" id=\"day\">일</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"start_container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"start_input\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">모집 마감 일자</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"start_select\" style=\"padding-left: 60px;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"control\" name=\"recruit_date\" placeholder=\"2019-01-01\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"text-muted\" id=\"day\">일</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"num_people\">\r\n");
      out.write("\t\t\t\t\t<div class=\"num_title\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-muted\">모집 인원</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"people\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"recruit_personnel\" style=\"font-size: 13px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\" selected>1명</option>\r\n");
      out.write("  \t\t\t\t\t\t\t<option value=\"2\">2명</option>\r\n");
      out.write("  \t\t\t\t\t\t\t<option value=\"3\">3명</option>\r\n");
      out.write("  \t\t\t\t\t\t\t<option value=\"4\">4명</option>\r\n");
      out.write("  \t\t\t\t\t\t\t<option value=\"5\">5명</option>\r\n");
      out.write("  \t\t\t\t\t\t\t<option value=\"6\">6명</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"project_insert_type\">\r\n");
      out.write("\t\t\t\t\t<h5 style=\"text-align: center; margin-top: 50px; margin-bottom: 20px;\"><b>프로젝트 등록 유형</b></h5>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\" id=\"col2\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/K-024.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-check\" style=\"padding-top: 20px; margin-bottom: 50px; text-align: center;\">\r\n");
      out.write("                \t\t\t\t<label class=\"form-check-label\">\r\n");
      out.write("                 \t\t\t\t <input class=\"form-check-input\" type=\"radio\" name=\"project_type\" id=\"exampleRadios1\" value=\"후원\">\r\n");
      out.write("                 \t\t\t\t\t <span class=\"circle\">\r\n");
      out.write("                  \t\t\t\t\t  <span class=\"check\"></span>\r\n");
      out.write("                  \t\t\t\t\t</span>\r\n");
      out.write("                \t\t\t\t</label>\r\n");
      out.write("              \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\" id=\"col2_2\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/K-025.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-check\" style=\"padding-top: 20px; margin-bottom: 50px; text-align: center;\">\r\n");
      out.write("                \t\t\t\t<label class=\"form-check-label\">\r\n");
      out.write("                 \t\t\t\t <input class=\"form-check-input\" type=\"radio\" name=\"project_type\" id=\"exampleRadios1\" value=\"파트너\">\r\n");
      out.write("                 \t\t\t\t\t <span class=\"circle\">\r\n");
      out.write("                  \t\t\t\t\t  <span class=\"check\"></span>\r\n");
      out.write("                  \t\t\t\t\t</span>\r\n");
      out.write("                \t\t\t\t</label>\r\n");
      out.write("              \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\" id=\"col2_3\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/K-026.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-check\" style=\"padding-top: 20px; margin-bottom: 50px; text-align: center;\">\r\n");
      out.write("                \t\t\t\t<label class=\"form-check-label\">\r\n");
      out.write("                 \t\t\t\t <input class=\"form-check-input\" type=\"radio\" name=\"project_type\" id=\"exampleRadios1\" value=\"후파\">\r\n");
      out.write("                 \t\t\t\t\t <span class=\"circle\">\r\n");
      out.write("                  \t\t\t\t\t  <span class=\"check\"></span>\r\n");
      out.write("                  \t\t\t\t\t</span>\r\n");
      out.write("                \t\t\t\t</label>\r\n");
      out.write("              \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 프로젝트 유형 끝! -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"insert_btn\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"등록\" class=\"btn btn-success\" style=\"width: 150px;\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div style=\"position:relative; bottom:630px; left:25px;\">\r\n");
      out.write("         \t<form id=\"fileUploadForm\" action=\"fileUpload.do\" method=\"post\" enctype=\"multipart/form-data\" accept-charset=\"UTF-8\">\r\n");
      out.write("                 <input type=\"file\" id=\"fileUpload\" name=\"fileUpload\"/>\r\n");
      out.write("               <input type=\"button\" class=\"btn btn-success\" value=\"업로드\" onClick=\"fileSubmit();\">\r\n");
      out.write("                &nbsp;&nbsp;\r\n");
      out.write("           \t</form>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t    function fileSubmit() {\r\n");
      out.write("\t        var formData = new FormData($(\"#fileUploadForm\")[0]);\r\n");
      out.write("\t        $.ajax({\r\n");
      out.write("\t            type : 'post',\r\n");
      out.write("\t            url : 'fileUpload.do',\r\n");
      out.write("\t            data : formData,\r\n");
      out.write("\t            processData : false,\r\n");
      out.write("\t            contentType : false,\r\n");
      out.write("\t            success : function(html) {\r\n");
      out.write("\t                alert(\"파일 업로드하였습니다.\");\r\n");
      out.write("\t                document.getElementById(\"board_file\").value=html;\r\n");
      out.write("\t               // alert(document.getElementById(\"board_file\").value);\r\n");
      out.write("\t            },\r\n");
      out.write("\t            error : function(error) {\r\n");
      out.write("\t                alert(\"포트폴리오 업로드에 실패하였습니다.\");\r\n");
      out.write("\t                console.log(error);\r\n");
      out.write("\t                console.log(error.status);\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t    }\t\r\n");
      out.write("</script>\r\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\"href=\"resources/assets/img/apple-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"resources/assets/img/favicon.png\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("<title>Material Kit by Creative Tim</title>\n");
      out.write("<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\n");
      out.write("<!-- Fonts and icons -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write("<!-- CSS Files -->\n");
      out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- CSS Just for demo purpose, don't include it in your project -->\n");
      out.write("<link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- fontawesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<footer class=\"footer\" data-background-color=\"black\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<nav class=\"float-left\">\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"text-align: left;\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t<h3><strong>About the Page</strong></h3>\n");
      out.write("\t\t\t\t\t\t<p>How much of a dream do you have in pudding You can realize your dreams. We will create opportunities. Challenge yourself. I support your high dream.</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t<h3><strong>Macker.</strong></h3>\n");
      out.write("\t\t\t\t\t\t<p> Team. 김이박 </p>\n");
      out.write("\t\t\t\t\t\t<p> With. 2019. 02. 08</p>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:250px;\"/>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
