/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-04-09 06:32:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class User_005fNoteView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/WEB-INF/inc/Partners_topbar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/admin_topbar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/index_topbar.jsp", Long.valueOf(1566188445000L));
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_funding/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/inc/user_message_sidebar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/client_topbar.jsp", Long.valueOf(1566188445000L));
    _jspx_dependants.put("/WEB-INF/inc/investor_topbar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_funding/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write(" \n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("   \n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("   \n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  \n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("  <meta charset=\"utf-8\" />\n");
      out.write("  \n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"resources/assets/img/apple-icon.png\">\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"resources/assets/img/favicon.png\">\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("  <title>\n");
      out.write("\t쪽지함\n");
      out.write("  </title>\n");
      out.write("  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\n");
      out.write("  <!--     Fonts and icons     -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write("  <!-- CSS Files -->\n");
      out.write("  <link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("  <!-- CSS Just for demo purpose, don't include it in your project -->\n");
      out.write("  <link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\n");
      out.write("  <!-- index.css 참조 -->\n");
      out.write("  <link href=\"resources/assets/css/index.css\" rel=\"stylesheet\" />\n");
      out.write("  <!-- fontawesome -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("  <link href=\"resources/assets/css/Project_RecruitmentList.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t// 쪽지 유효성 검사\n");
      out.write("\tfunction note_content(){\n");
      out.write("\t\tvar content = document.getElementById(\"content\");\n");
      out.write("\t\tif(content.value == \"\"){\n");
      out.write("\t\t\talert(\"쪽지 내용을 입력해 주세요.\");\n");
      out.write("\t\t\tcontent.focus();\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t$(function(){\n");
      out.write("\t\t// 받은 쪽지 삭제 확인창 쿼리\n");
      out.write("\t\t$(\"#delete_bt\").click(function(){\n");
      out.write("\t\t\tvar result = confirm(\"쪽지를 삭제하시겠습니까?\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(result){\n");
      out.write("\t\t\t\tlocation.href='receive_delete.do?message_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&page=1';\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t//취소를 누르면 변화없음\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t// 보낸 쪽지 삭제 확인창 쿼리\n");
      out.write("\t\t$(\"#delete_bt2\").click(function(){\n");
      out.write("\t\t\tvar result = confirm(\"쪽지를 삭제하시겠습니까?\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(result){\n");
      out.write("\t\t\t\tlocation.href='send_delete.do?message_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&page=1';\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t//취소를 누르면 변화없음\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<body class=\"index-page sidebar-collapse\">\n");
      out.write("\t<div class=\"main main-raised\">\n");
      out.write("\t\t<div class=\"section section-basic\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write(" <link href=\"resources/assets/css/pw_change.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div class=\"col-md-3\" id=\"sidebar\">\n");
      out.write("\t\t<b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_type }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>&nbsp;&nbsp; <a href=\"user_infoUpdate.do\"><b>기본정보 수정하기</b></a>\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t<div class=\"user_info\">\n");
      out.write("\t\t\t<img src=\"resources/assets/img/Teemo.png\"\n");
      out.write("\t\t\t\tclass=\"user_img rounded-circle img-fluid\" />\n");
      out.write("\t\t\t<div class=\"user_info\">\n");
      out.write("\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t<div class=\"col-md-12\">\n");
      out.write("\n");
      out.write("\t\t\t<a class=\"btn btn-link2 active\" href=\"message_re.do?page=1\">받은 쪽지함</a> \n");
      out.write("\t\t\t<a class=\"btn btn-link2 active\" href=\"message_se.do?page=1\">보낸 쪽지함</a> \n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t\t\t<!-- 왼쪽 사이드 바 div -->\n");
      out.write("\t\t\t\t<div class=\"col\" style=\"margin-top: -30px;\">\n");
      out.write("\t\t\t\t<div class=\"col col-md-15\" id=\"apply\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f9(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<h4><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 쪽지 전송 모달창 --> \n");
      out.write("\n");
      out.write("\t<div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<!-- The Modal -->\n");
      out.write("\t\t\t<div class=\"modal\" id=\"myModal\">\n");
      out.write("\t\t\t\t<div class=\"modal-dialog \">\n");
      out.write("\t\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t\t<!-- Modal Header -->\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"modal-title\">\n");
      out.write("\t\t\t\t\t\t\t\t<b style=\"padding-left: 180px;\">쪽지쓰기</b>\n");
      out.write("\t\t\t\t\t\t\t</h3>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- Modal body -->\n");
      out.write("\t\t\t\t\t\t<!-- 값을 전송하는 부분 -->\n");
      out.write("\t\t\t\t\t\t<form action=\"message_reply.do?page=1\" method=\"post\" onsubmit=\"return note_content();\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"sender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<!-- 쪽지 내용 작성하는 부분 -->\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\n");
      out.write("\t\t\t\t\t\t\t\t\t<b id=\"min\">받는사람&nbsp;</b>\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"reader\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_sender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"border: none;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t<h4>\n");
      out.write("\t\t\t\t\t\t\t\t<b>내용&nbsp;</b>\n");
      out.write("\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t<textarea rows=\"10\" cols=\"40\" class=\"form-control\" name=\"content\" id=\"content\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<!-- Modal footer -->\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-warning\" value=\"보내기\" id=\"send\"/>\n");
      out.write("\t\t\t\t\t\t\t<!-- data-dismiss : 모달창 닫기 -->\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-default\" value=\"취소\" data-dismiss=\"modal\"/>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\"href=\"resources/assets/img/apple-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"resources/assets/img/favicon.png\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("<title>Material Kit by Creative Tim</title>\n");
      out.write("<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\n");
      out.write("<!-- Fonts and icons -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write("<!-- CSS Files -->\n");
      out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- CSS Just for demo purpose, don't include it in your project -->\n");
      out.write("<link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- fontawesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<footer class=\"footer\" data-background-color=\"black\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<nav class=\"float-left\">\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"text-align: left;\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t<h3><strong>About the Page</strong></h3>\n");
      out.write("\t\t\t\t\t\t<p>How much of a dream do you have in pudding You can realize your dreams. We will create opportunities. Challenge yourself. I support your high dream.</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t<h3><strong>Macker.</strong></h3>\n");
      out.write("\t\t\t\t\t\t<p> Team. 김이박 </p>\n");
      out.write("\t\t\t\t\t\t<p> With. 2019. 02. 08</p>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:250px;\"/>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("  </body>\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /User_NoteView.jsp(9,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          out.write('\n');
          out.write(' ');
          out.write("\r\n");
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta charset=\"utf-8\" />\r\n");
          out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"resources/assets/img/apple-icon.png\">\r\n");
          out.write("  <link rel=\"icon\" type=\"image/png\" href=\"resources/assets/img/favicon.png\">\r\n");
          out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
          out.write("  <title>\r\n");
          out.write("    Puding\r\n");
          out.write("  </title>\r\n");
          out.write("  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\r\n");
          out.write("  <!--     Fonts and icons     -->\r\n");
          out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\r\n");
          out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\r\n");
          out.write("   <!-- CSS Files -->\r\n");
          out.write("   <link href=\"resources/assets/css/material-kit.css?v=2.0.5\" rel=\"stylesheet\" />\r\n");
          out.write(" \r\n");
          out.write("  <!-- CSS Just for demo purpose, don't include it in your project -->\r\n");
          out.write("  <link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\r\n");
          out.write("\r\n");
          out.write("</head>\r\n");
          out.write("\r\n");
          out.write("<body class=\"index-page sidebar-collapse\">\r\n");
          out.write("  <nav class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\" color-on-scroll=\"100\" id=\"sectionsNav\">\r\n");
          out.write("    <div class=\"container\">\r\n");
          out.write("      <div class=\"navbar-translate\">\r\n");
          out.write("        <a href=\"main.do\"><img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:100px;\"/></a>\r\n");
          out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\" data-target=\"#index_topbar\">\r\n");
          out.write("          <span class=\"sr-only\">Toggle navigation</span>\r\n");
          out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
          out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
          out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
          out.write("        </button>\r\n");
          out.write("      </div>\r\n");
          out.write("      <div class=\"collapse navbar-collapse\" id=\"index_topbar\">\r\n");
          out.write("                <ul class=\"navbar-nav\">\r\n");
          out.write("                  <li class=\"nav-item\" id=\"item1\">\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("               \" class=\"nav-link\"style=\"color:white\" id=\"login\">프로젝트 등록</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  \" class=\"nav-link\" style=\"color:white\">프로젝트 찾기</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            \" class=\"nav-link\" style=\"color:white\">파트너스 목록</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"question.do\" class=\"nav-link\" style=\"color:white\">이용 방법</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                </ul>\r\n");
          out.write("                <ul class=\"navbar-nav ml-auto\">\r\n");
          out.write("                    <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"login.do\" class=\"nav-link\" style=\"color:white\">Login</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"join.do\" class=\"nav-link\" style=\"color:white\">Join</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("               </ul>\r\n");
          out.write("       </div>\r\n");
          out.write("    </div>\r\n");
          out.write("  </nav>\r\n");
          out.write("  \r\n");
          out.write("\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          out.write('\n');
          out.write(' ');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/inc/index_topbar.jsp(43,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                JAVASCRIPT:alert('로그인을 해주세요!');\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/inc/index_topbar.jsp(50,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("               JAVASCRIPT:alert('로그인을 해주세요!');\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/inc/index_topbar.jsp(57,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                JAVASCRIPT:alert('로그인을 해주세요!');\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /User_NoteView.jsp(13,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '파트너스' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write(' ');
          out.write(' ');
          out.write("\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("<title>Puding</title>\r\n");
          out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\r\n");
          out.write("<link rel=\"stylesheet\"\r\n");
          out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
          out.write("<script\r\n");
          out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
          out.write("<script\r\n");
          out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
          out.write(" <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
          out.write("\t<!-- 구글로그인api -->\r\n");
          out.write("<script src=\"https://apis.google.com/js/platform.js\" async defer></script>\r\n");
          out.write("<meta name=\"google-signin-scope\" content=\"profile email\">\r\n");
          out.write("<meta name=\"google-signin-client_id\" content=\"194507075586-fqdh9s1af0jq81cq27hqe5m9fim0692t.apps.googleusercontent.com\">\r\n");
          out.write("\t\r\n");
          out.write("<style type=\"text/css\">\r\n");
          out.write("#ho:hover {\r\n");
          out.write("\tposition: relative;\r\n");
          out.write("\ttop: calc(100% - 0.125rem);\r\n");
          out.write("\tborder-bottom: 4px solid #FFA7A7;\r\n");
          out.write("\tleft: 50%;\r\n");
          out.write("\tright: 50%;\r\n");
          out.write("\ttransition: all 0.5s ease;\r\n");
          out.write("\tleft: 0;\r\n");
          out.write("\tright: 0;\r\n");
          out.write("\ttransition: all 0.5s ease;\r\n");
          out.write("}\r\n");
          out.write("</style>\r\n");
          out.write("</head>\r\n");
          out.write("\r\n");
          out.write("<body>\r\n");
          out.write("\t<nav\r\n");
          out.write("\t\tclass=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\r\n");
          out.write("\t\tid=\"sectionsNav\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"navbar-translate\">\r\n");
          out.write("\t\t\t\t<a href=\"main.do\"><img\r\n");
          out.write("\t\t\t\t\tsrc=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\"\r\n");
          out.write("\t\t\t\t\tstyle=\"width: 100px;\" /></a>\r\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\r\n");
          out.write("\t\t\t\t</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a\r\n");
          out.write("\t\t\t\t\t\thref=\"partner_mypage.do?user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&page=1\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\">나의 푸딩</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_list.do?page=1\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" style=\"color: white\">프로젝트 찾기</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"partner_list.do\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" style=\"color: white\">파트너스 목록</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"question.do\" class=\"nav-link\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\">이용 방법</a></li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\"><a\r\n");
          out.write("\t\t\t\t\t\thref=\"message_re.do?page=1\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"btn btn-rose btn-raised btn-fab btn-round\"> <i\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"material-icons\">email</i>\r\n");
          out.write("\t\t\t\t\t</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"logOut.do\" class=\"nav-link\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\" onclick=\"signOut();\">Logout</a></li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</nav>\r\n");
          out.write("\r\n");
          out.write("\t<nav\r\n");
          out.write("\t\tclass=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\r\n");
          out.write("\t\tid=\"sectionsNav2\"\r\n");
          out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"navbar-translate\" style=\"width: 100px;\">\r\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\r\n");
          out.write("\t\t\t\t</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\" style=\"color: black;\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"partners_profile.do\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">내 프로필</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"user_typeUpdate.do\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">계정 유형 변경\r\n");
          out.write("\t\t\t\t\t\t\t신청</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_supportList.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">지원 내역</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a\r\n");
          out.write("\t\t\t\t\t\thref=\"project_ing.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">진행중인 프로젝트</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_end.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">완료한 프로젝트</a></li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t</nav>\r\n");
          out.write("\t<br>\r\n");
          out.write("\t<br>\r\n");
          out.write("\t<br>\r\n");
          out.write("<script>\r\n");
          out.write("  function signOut() {\r\n");
          out.write("    var auth2 = gapi.auth2.getAuthInstance();\r\n");
          out.write("    auth2.signOut().then(function () {\r\n");
          out.write("      console.log('User signed out.');\r\n");
          out.write("    });\r\n");
          out.write("  }\r\n");
          out.write("</script>\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          out.write('\n');
          out.write(' ');
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /User_NoteView.jsp(17,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '클라이언트' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write(' ');
          out.write(' ');
          out.write("\n");
          out.write("<html>\n");
          out.write("<head>\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
          out.write("<title>Puding</title>\n");
          out.write("\n");
          out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
          out.write("<link rel=\"stylesheet\"\n");
          out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\n");
          out.write("<script\n");
          out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
          out.write("<script\n");
          out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\n");
          out.write(" <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n");
          out.write("\t<!-- 구글로그인api -->\n");
          out.write("<script src=\"https://apis.google.com/js/platform.js\" async defer></script>\n");
          out.write("<meta name=\"google-signin-scope\" content=\"profile email\">\n");
          out.write("<meta name=\"google-signin-client_id\" content=\"194507075586-fqdh9s1af0jq81cq27hqe5m9fim0692t.apps.googleusercontent.com\">\n");
          out.write("\t\n");
          out.write("<style type=\"text/css\">\n");
          out.write("#ho:hover {\n");
          out.write("\tposition: relative;\n");
          out.write("\ttop: calc(100% - 0.125rem);\n");
          out.write("\tborder-bottom: 4px solid #FFA7A7;\n");
          out.write("\tleft: 50%;\n");
          out.write("\tright: 50%;\n");
          out.write("\ttransition: all 0.5s ease;\n");
          out.write("\tleft: 0;\n");
          out.write("\tright: 0;\n");
          out.write("\ttransition: all 0.5s ease;\n");
          out.write("}\n");
          out.write("</style>\n");
          out.write("\n");
          out.write("</head>\n");
          out.write("<body>\n");
          out.write("\n");
          out.write("   <nav\n");
          out.write("      class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\n");
          out.write("      id=\"sectionsNav\">\n");
          out.write("      <div class=\"container\">\n");
          out.write("         <div class=\"navbar-translate\">\n");
          out.write("            <!-- 상단 메뉴바 -->\n");
          out.write("            <a href=\"main.do\"><img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:100px;\"/></a>\n");
          out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
          out.write("               aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
          out.write("               <span class=\"sr-only\">Toggle navigation</span> \n");
          out.write("               <span class=\"navbar-toggler-icon\"></span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span>\n");
          out.write("            </button>\n");
          out.write("         </div>\n");
          out.write("         <div class=\"collapse navbar-collapse\">\n");
          out.write("            <ul class=\"navbar-nav\">\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"client_mypage.do\" class=\"nav-link\">나의\n");
          out.write("\t\t\t\t\t\t\t푸딩</a></li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\">\n");
          out.write("\t\t\t\t\t\t<a href=\"project_insert.do\" class=\"nav-link\" style=\"color: white\">프로젝트 등록</a>\n");
          out.write("\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_list.do?page=1\"\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" style=\"color: white\">프로젝트 찾기</a></li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a\n");
          out.write("\t\t\t\t\t\thref=\"partner_list.do\" class=\"nav-link\"\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\">파트너스 목록</a></li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"question.do\" class=\"nav-link\"\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\">이용 방법</a></li>\n");
          out.write("\t\t\t\t</ul>\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\">\n");
          out.write("\t\t\t\t\t<a href=\"message_re.do?page=1\" class=\"btn btn-rose btn-raised btn-fab btn-round\"> <i\n");
          out.write("\t\t\t\t\t\tclass=\"material-icons\">email</i></a> \n");
          out.write("\t\t\t\t\t<!-- <a class=\"btn btn-rose btn-raised btn-fab btn-round\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a> -->\n");
          out.write("\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"logOut.do\" class=\"nav-link\"\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\" onclick=\"signOut();\">Logout</a></li>\n");
          out.write("\t\t\t\t\t\t\n");
          out.write("\t\t\t\t</ul>\n");
          out.write("\t\t\t</div>\n");
          out.write("\t\t</div>\n");
          out.write("\t</nav>\n");
          out.write("\n");
          out.write("\t<nav class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\" id=\"sectionsNav\"\n");
          out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\n");
          out.write("   <nav\n");
          out.write("      class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\n");
          out.write("      id=\"sectionsNav\"\n");
          out.write("      style=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\n");
          out.write("      <div class=\"container\">\n");
          out.write("         <div class=\"navbar-translate\" style=\"width: 100px;\">\n");
          out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
          out.write("               aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
          out.write("               <span class=\"sr-only\">Toggle navigation</span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span>\n");
          out.write("            </button>\n");
          out.write("         </div>\n");
          out.write("\n");
          out.write("         <div class=\"collapse navbar-collapse\">\n");
          out.write("            <ul class=\"navbar-nav\" style=\"color:black;\">\n");
          out.write("               <li class=\"nav-item\"><a href=\"project_inspectionList.do?user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" \n");
          out.write("               class=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">검수중인 프로젝트</a></li>\n");
          out.write("               <li class=\"nav-item\"><a href=\"project_recruitmentList.do?user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link\" id=\"ho\"\n");
          out.write("                  style=\"padding-top: 17px;\">지원자 모집 중</a></li>\n");
          out.write("                <li class=\"nav-item\"><a href=\"project_ing.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link\" id=\"ho\"\n");
          out.write("                  style=\"padding-top: 17px;\">진행중인 프로젝트</a></li>\n");
          out.write("                  <li class=\"nav-item\"><a href=\"project_end.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link\" id=\"ho\"\n");
          out.write("                  style=\"padding-top: 17px;\">완료한 프로젝트</a></li>\n");
          out.write("                  <li class=\"nav-item\"><a href=\"user_typeUpdate.do\" class=\"nav-link\" id=\"ho\"\n");
          out.write("                  style=\"padding-top: 17px;\">계정 유형 변경 신청</a></li>\n");
          out.write("            </ul>\n");
          out.write("         </div>\n");
          out.write("         </div>\n");
          out.write("         </nav>\n");
          out.write("         \n");
          out.write("   </nav>\n");
          out.write("   <br><br><br>\n");
          out.write("\n");
          out.write("<script>\n");
          out.write("  function signOut() {\n");
          out.write("    var auth2 = gapi.auth2.getAuthInstance();\n");
          out.write("    auth2.signOut().then(function () {\n");
          out.write("      console.log('User signed out.');\n");
          out.write("    });\n");
          out.write("  }\n");
          out.write("</script>\n");
          out.write("</body>\n");
          out.write("</html>");
          out.write('\n');
          out.write(' ');
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /User_NoteView.jsp(21,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '투자자' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write(' ');
          out.write(' ');
          out.write("\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("<title>Puding</title>\r\n");
          out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\r\n");
          out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
          out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
          out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
          out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
          out.write("  <!-- 구글로그인api -->\r\n");
          out.write("<script src=\"https://apis.google.com/js/platform.js\" async defer></script>\r\n");
          out.write("<meta name=\"google-signin-scope\" content=\"profile email\">\r\n");
          out.write("<meta name=\"google-signin-client_id\" content=\"194507075586-fqdh9s1af0jq81cq27hqe5m9fim0692t.apps.googleusercontent.com\">\r\n");
          out.write("  \r\n");
          out.write("\r\n");
          out.write("<style type=\"text/css\">\r\n");
          out.write("\r\n");
          out.write("#ho:hover {\r\n");
          out.write("\tposition: relative;\r\n");
          out.write("\ttop: calc(100% - 0.125rem);\r\n");
          out.write("\tborder-bottom: 4px solid #FFA7A7;\r\n");
          out.write("\tleft: 50%;\r\n");
          out.write("\tright: 50%;\r\n");
          out.write("\ttransition: all 0.5s ease;\r\n");
          out.write(" \tleft: 0;\r\n");
          out.write("  \tright: 0;\r\n");
          out.write(" \ttransition: all 0.5s ease;\r\n");
          out.write("}\r\n");
          out.write("</style>\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("\t<nav\r\n");
          out.write("\t\tclass=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\r\n");
          out.write("\t\tid=\"sectionsNav\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"navbar-translate\">\r\n");
          out.write("\t\t\t\t<a href=\"main.do\"><img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:100px;\"/></a>\r\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\" >\r\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\r\n");
          out.write("\t\t\t\t</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
          out.write("\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"project_list.do?page=1\" class=\"nav-link\">프로젝트 찾기</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"partner_list.do\" class=\"nav-link\">파트너스 목록</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"question.do\" class=\"nav-link\">이용 방법</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\">\r\n");
          out.write("\t\t\t\t\t\t<a href=\"message_re.do?page=1\" class=\"btn btn-rose btn-raised btn-fab btn-round\">\r\n");
          out.write("\t\t\t\t\t\t\t <i class=\"material-icons\">email</i>\r\n");
          out.write("\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
          out.write("\t\t\t\t\t\t<a href=\"logOut.do\" class=\"nav-link\"style=\"color: white\" onclick=\"signOut();\">Logout</a>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</nav>\r\n");
          out.write("\r\n");
          out.write("\t<nav\r\n");
          out.write("\t\tclass=\"navbar navbar-transparent fixed-top navbar-expand-lg\"\r\n");
          out.write("\t\tid=\"sectionsNav2\"\r\n");
          out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"navbar-translate\" style=\"width: 100px;\">\r\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" data-target=\"#investor_topbar\">\r\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\r\n");
          out.write("\t\t\t\t</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"investor_topbar\">\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\" style=\"color:black;\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"user_coin.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link\" id=\"ho\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">코인 관리</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"user_typeUpdate.do\" class=\"nav-link\" id=\"ho\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">계정 유형 변경 신청</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_fundinglist.do\" class=\"nav-link\" id=\"ho\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">투자한 프로젝트</a></li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\n");
          out.write("\t</nav>\r\n");
          out.write("\t<br>\r\n");
          out.write("\t<br>\r\n");
          out.write("\t<br>\r\n");
          out.write("<script>\r\n");
          out.write("  function signOut() {\r\n");
          out.write("    var auth2 = gapi.auth2.getAuthInstance();\r\n");
          out.write("    auth2.signOut().then(function () {\r\n");
          out.write("      console.log('User signed out.');\r\n");
          out.write("    });\r\n");
          out.write("  }\r\n");
          out.write("</script>\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          out.write('\n');
          out.write(' ');
          out.write(' ');
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /User_NoteView.jsp(25,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '관리자' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write(' ');
          out.write(' ');
          out.write("\n");
          out.write("<html>\n");
          out.write("<head>\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
          out.write("<title>Puding</title>\n");
          out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
          out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\n");
          out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
          out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\n");
          out.write("<!--  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script> -->\n");
          out.write("\n");
          out.write("<style type=\"text/css\">\n");
          out.write("\n");
          out.write("#ho:hover {\n");
          out.write("\tposition: relative;\n");
          out.write("\ttop: calc(100% - 0.125rem);\n");
          out.write("\tborder-bottom: 4px solid #FFA7A7;\n");
          out.write("\tleft: 50%;\n");
          out.write("\tright: 50%;\n");
          out.write("\ttransition: all 0.5s ease;\n");
          out.write(" \tleft: 0;\n");
          out.write("  \tright: 0;\n");
          out.write(" \ttransition: all 0.5s ease;\n");
          out.write("}\n");
          out.write("</style>\n");
          out.write("</head>\n");
          out.write("<body>\n");
          out.write("\t<nav\n");
          out.write("\t\tclass=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\n");
          out.write("\t\tid=\"sectionsNav\">\n");
          out.write("\t\t<div class=\"container\">\n");
          out.write("\t\t\t<div class=\"navbar-translate\">\n");
          out.write("\t\t\t\t<a href=\"main.do\"><img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:100px;\"/></a>\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\" >\n");
          out.write("\t\t\t\t\t\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\n");
          out.write("\t\t\t\t</button>\n");
          out.write("\t\t\t</div>\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\">\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\">\n");
          out.write("\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\">\n");
          out.write("                    <a href=\"project_list.do?page=1\" class=\"nav-link\">프로젝트 찾기</a>\n");
          out.write("                  </li>\n");
          out.write("\t\t\t\t</ul>\n");
          out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\">\n");
          out.write("\t\t\t\t\t\t<a href=\"message_re.do?page=1\" class=\"btn btn-rose btn-raised btn-fab btn-round\">\n");
          out.write("\t\t\t\t\t\t\t <i class=\"material-icons\">email</i>\n");
          out.write("\t\t\t\t\t\t</a>\n");
          out.write("\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\">\n");
          out.write("\t\t\t\t\t\t<a href=\"logOut.do\" class=\"nav-link\"style=\"color: white\">Log out</a>\n");
          out.write("\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t</ul>\n");
          out.write("\t\t\t</div>\n");
          out.write("\t\t</div>\n");
          out.write("\t</nav>\n");
          out.write("\n");
          out.write("\t<nav\n");
          out.write("\t\tclass=\"navbar navbar-transparent fixed-top navbar-expand-lg\"\n");
          out.write("\t\tid=\"sectionsNav2\"\n");
          out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\n");
          out.write("\t\t<div class=\"container\">\n");
          out.write("\t\t\t<div class=\"navbar-translate\" style=\"width: 100px;\">\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" data-target=\"#investor_topbar\">\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\n");
          out.write("\t\t\t\t</button>\n");
          out.write("\t\t\t</div>\n");
          out.write("\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"investor_topbar\">\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\" style=\"color:black;\">\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"admin_coin.do\" class=\"nav-link\" id=\"ho\"\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">환불 신청 내역</a></li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"admin_inspectionList.do\" class=\"nav-link\" id=\"ho\"\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">프로젝트 신청 내역</a></li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"admin_typeupdate.do\" class=\"nav-link\" id=\"ho\"\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">계정 유형 신청</a></li>\n");
          out.write("\t\t\t\t</ul>\n");
          out.write("\t\t\t</div>\n");
          out.write("\t\t\t</div>\n");
          out.write("\t\n");
          out.write("\t</nav>\n");
          out.write("\t<br>\n");
          out.write("\t<br>\n");
          out.write("\t<br>\n");
          out.write("</body>\n");
          out.write("</html>");
          out.write('\n');
          out.write(' ');
          out.write(' ');
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /User_NoteView.jsp(104,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_reader eq userdto.user_id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<input type=\"button\" class=\"btn btn-default\" id=\"delete_bt\" value=\"삭제\">\n");
          out.write("\t\t\t\t\t<input type=\"button\" class=\"btn btn-warning\" data-toggle=\"modal\" data-target=\"#myModal\" value=\"답장\">\n");
          out.write("\t\t\t\t\t<input type=\"button\" class=\"btn btn-success\" value=\"목록으로\" onclick=\"location.href='re_list.do?page=1'\"/>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f9_reused = false;
    try {
      _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f9.setParent(null);
      // /User_NoteView.jsp(110,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_reader ne userdto.user_id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
      if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<input type=\"button\" class=\"btn btn-default\" id=\"delete_bt2\" value=\"삭제\">\t\n");
          out.write("\t\t\t\t\t<input type=\"button\" class=\"btn btn-success\" value=\"목록으로\" onclick=\"location.href='se_list.do?page=1'\"/>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
      _jspx_th_c_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /User_NoteView.jsp(117,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_reader eq userdto.user_id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<h4><b>보낸사람 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_sender }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b></h4>\n");
          out.write("\t\t\t\t\t<h4><b>받은날짜 :&nbsp;");
          if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("</b></h4>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /User_NoteView.jsp(119,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_senddate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /User_NoteView.jsp(119,24) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<h4><b>받는사람 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_reader }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b></h4>\n");
          out.write("\t\t\t\t\t<h4><b>보낸날짜 :&nbsp;");
          if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("</b></h4>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /User_NoteView.jsp(124,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MessageView.message_senddate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /User_NoteView.jsp(124,24) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }
}
