/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-04-09 07:02:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class User_005fInfoUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/WEB-INF/inc/Partners_topbar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/investor_sidebar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project_funding/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/inc/partners_sidebar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/client_sidebar.jsp", Long.valueOf(1566188446000L));
    _jspx_dependants.put("/WEB-INF/inc/client_topbar.jsp", Long.valueOf(1566188445000L));
    _jspx_dependants.put("/WEB-INF/inc/investor_topbar.jsp", Long.valueOf(1566188446000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write(" \n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write(" \n");
      out.write(" ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"resources/assets/img/apple-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"resources/assets/img/favicon.png\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("<title>\n");
      out.write(" \t회원정보수정\n");
      out.write("</title>\n");
      out.write("<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\n");
      out.write("<!-- Fonts and icons -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write("<!-- CSS Files -->\n");
      out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- CSS Just for demo purpose, don't include it in your project -->\n");
      out.write("<link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- index.css 참조 -->\n");
      out.write("<link href=\"resources/assets/css/index.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- fontawesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\n");
      out.write("<link href=\"resources/assets/css/User_InfoUpdate.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 다음도로명주소사용시 필요 -->\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\n");
      out.write("<script charset=\"UTF-8\" type=\"text/javascript\"\n");
      out.write("\tsrc=\"http://t1.daumcdn.net/postcode/api/core/180928/1538455030985/180928.js\"></script>\n");
      out.write("<script>\n");
      out.write("\tfunction roadaddr() {\n");
      out.write("\t\tnew daum.Postcode({\n");
      out.write("\t\t\toncomplete : function(data) {\n");
      out.write("\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\n");
      out.write("\n");
      out.write("\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 조합한다.\n");
      out.write("\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\n");
      out.write("\t\t\t\tvar fullRoadAddr = data.roadAddress; // 도로명 주소 변수\n");
      out.write("\t\t\t\tvar extraRoadAddr = ''; // 도로명 조합형 주소 변수\n");
      out.write("\n");
      out.write("\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\n");
      out.write("\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\n");
      out.write("\t\t\t\tif (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\n");
      out.write("\t\t\t\t\textraRoadAddr += data.bname;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\n");
      out.write("\t\t\t\tif (data.buildingName !== '' && data.apartment === 'Y') {\n");
      out.write("\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\n");
      out.write("\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t// 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\n");
      out.write("\t\t\t\tif (extraRoadAddr !== '') {\n");
      out.write("\t\t\t\t\textraRoadAddr = ' (' + extraRoadAddr + ')';\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t// 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.\n");
      out.write("\t\t\t\tif (fullRoadAddr !== '') {\n");
      out.write("\t\t\t\t\tfullRoadAddr += extraRoadAddr;\n");
      out.write("\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t// 도로명 주소 값 얻어오기\n");
      out.write("\t\t\t\tdocument.getElementById('roadAddress').value = fullRoadAddr;\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}).open();\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"index-page sidebar-collapse\">\n");
      out.write("\t<div class=\"main main-raised\">\n");
      out.write("\t\t<div class=\"section section-basic\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t \n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t \n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t<!-- 왼쪽 사이드 바 div -->\n");
      out.write("\t\t\t\t<div class=\"col\" style=\"margin-top: -30px;\">\n");
      out.write("\t\t\t\t<div class=\"col col-md-15\">\n");
      out.write("\t\t\t\t\t<h3><b>회원정보수정</b></h3>\n");
      out.write("\t\t\t\t\t<p class=\"text-muted\" style=\"font-size: 13px;\">회원정보를 수정할 수 있습니다.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-md-15\">\n");
      out.write("\t\t\t\t\t\t\t\t<h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>계정 정보</b>\n");
      out.write("\t\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user_idemail\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>아이디</b>&nbsp;&nbsp;&nbsp; <p class=\"text-muted\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>이메일</b>&nbsp;&nbsp;&nbsp; <p class=\"text-muted\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"user_info_up\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>기본 정보</b>\n");
      out.write("\t\t\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"fileUploadForm\" action=\"fileUpload.do\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"user_info_write\" id=\"profile_img\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<b>프로필 사진</b>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" id=\"fileUpload\" name=\"fileUpload\" class=\"form-control\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-warning\"onClick=\"fileSubmit();\" value=\"업로드\" style=\"float: right;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"user_infoUpdateAction.do\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"imageupload\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"user_img\" name=\"user_img\" hidden=\"\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user_info_write\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>* 이름</b>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"user_name\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user_info_write\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>* 성별</b>&nbsp;&nbsp;</br></br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-check\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-check-label\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"user_sex\" id=\"exampleRadios2\" value=\"man\" checked> 남자\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"check\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-check\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-check-label\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-check-input\" type=\"radio\" name=\"user_sex\" id=\"exampleRadios1\" value=\"woman\"> 여자\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"circle\">\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"check\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t</label>\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user_info_write\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>* 생년월일</b>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"user_birth\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_birth }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user_info_write\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>* 주소</b>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a onclick=\"roadaddr()\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"user_addr\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_addr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" class=\"form-control\" id=\"roadAddress\" readonly=\"readonly\" style=\"background-color: white;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-warning\" value=\"주소 검색\" style=\"float: right;\" onclick=\"roadaddr()\"/> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user_bt\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success\" value=\"변경완료\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write("\tfunction fileSubmit() {\n");
      out.write("\tvar formData = new FormData($(\"#fileUploadForm\")[0]);\n");
      out.write("\t$.ajax({\n");
      out.write("\ttype : 'post',\n");
      out.write("\turl : 'fileUpload.do',\n");
      out.write("\tdata : formData,\n");
      out.write("\tprocessData : false,\n");
      out.write("\tcontentType : false,\n");
      out.write("\tsuccess : function(html) {\n");
      out.write("\talert(\"사진을 업로드하였습니다.\");\n");
      out.write("\tdocument.getElementById(\"user_img\").value=html;\n");
      out.write("\t//alert(document.getElementById(\"user_img\").value);\n");
      out.write("\t \t\t\t },\n");
      out.write("\terror : function(error) {\n");
      out.write("\talert(\"사진 업로드에 실패하였습니다.\");\n");
      out.write("\tconsole.log(error);\n");
      out.write("\tconsole.log(error.status);\n");
      out.write("\t}\n");
      out.write("\t});\n");
      out.write("\t}\n");
      out.write("\t</script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"76x76\"href=\"resources/assets/img/apple-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"resources/assets/img/favicon.png\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("<title>Material Kit by Creative Tim</title>\n");
      out.write("<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />\n");
      out.write("<!-- Fonts and icons -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write("<!-- CSS Files -->\n");
      out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- CSS Just for demo purpose, don't include it in your project -->\n");
      out.write("<link href=\"resources/assets/demo/demo.css\" rel=\"stylesheet\" />\n");
      out.write("<!-- fontawesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\" integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<footer class=\"footer\" data-background-color=\"black\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<nav class=\"float-left\">\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"text-align: left;\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t<h3><strong>About the Page</strong></h3>\n");
      out.write("\t\t\t\t\t\t<p>How much of a dream do you have in pudding You can realize your dreams. We will create opportunities. Challenge yourself. I support your high dream.</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t<h3><strong>Macker.</strong></h3>\n");
      out.write("\t\t\t\t\t\t<p> Team. 김이박 </p>\n");
      out.write("\t\t\t\t\t\t<p> With. 2019. 02. 08</p>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:250px;\"/>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /User_InfoUpdate.jsp(8,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '파트너스' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write("\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("<title>Puding</title>\r\n");
          out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\r\n");
          out.write("<link rel=\"stylesheet\"\r\n");
          out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
          out.write("<script\r\n");
          out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
          out.write("<script\r\n");
          out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
          out.write(" <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
          out.write("\t<!-- 구글로그인api -->\r\n");
          out.write("<script src=\"https://apis.google.com/js/platform.js\" async defer></script>\r\n");
          out.write("<meta name=\"google-signin-scope\" content=\"profile email\">\r\n");
          out.write("<meta name=\"google-signin-client_id\" content=\"194507075586-fqdh9s1af0jq81cq27hqe5m9fim0692t.apps.googleusercontent.com\">\r\n");
          out.write("\t\r\n");
          out.write("<style type=\"text/css\">\r\n");
          out.write("#ho:hover {\r\n");
          out.write("\tposition: relative;\r\n");
          out.write("\ttop: calc(100% - 0.125rem);\r\n");
          out.write("\tborder-bottom: 4px solid #FFA7A7;\r\n");
          out.write("\tleft: 50%;\r\n");
          out.write("\tright: 50%;\r\n");
          out.write("\ttransition: all 0.5s ease;\r\n");
          out.write("\tleft: 0;\r\n");
          out.write("\tright: 0;\r\n");
          out.write("\ttransition: all 0.5s ease;\r\n");
          out.write("}\r\n");
          out.write("</style>\r\n");
          out.write("</head>\r\n");
          out.write("\r\n");
          out.write("<body>\r\n");
          out.write("\t<nav\r\n");
          out.write("\t\tclass=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\r\n");
          out.write("\t\tid=\"sectionsNav\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"navbar-translate\">\r\n");
          out.write("\t\t\t\t<a href=\"main.do\"><img\r\n");
          out.write("\t\t\t\t\tsrc=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\"\r\n");
          out.write("\t\t\t\t\tstyle=\"width: 100px;\" /></a>\r\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\r\n");
          out.write("\t\t\t\t</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a\r\n");
          out.write("\t\t\t\t\t\thref=\"partner_mypage.do?user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&page=1\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\">나의 푸딩</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_list.do?page=1\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" style=\"color: white\">프로젝트 찾기</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"partner_list.do\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" style=\"color: white\">파트너스 목록</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"question.do\" class=\"nav-link\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\">이용 방법</a></li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\"><a\r\n");
          out.write("\t\t\t\t\t\thref=\"message_re.do?page=1\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"btn btn-rose btn-raised btn-fab btn-round\"> <i\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"material-icons\">email</i>\r\n");
          out.write("\t\t\t\t\t</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"logOut.do\" class=\"nav-link\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\" onclick=\"signOut();\">Logout</a></li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</nav>\r\n");
          out.write("\r\n");
          out.write("\t<nav\r\n");
          out.write("\t\tclass=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\r\n");
          out.write("\t\tid=\"sectionsNav2\"\r\n");
          out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"navbar-translate\" style=\"width: 100px;\">\r\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\r\n");
          out.write("\t\t\t\t</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\" style=\"color: black;\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"partners_profile.do\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">내 프로필</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"user_typeUpdate.do\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">계정 유형 변경\r\n");
          out.write("\t\t\t\t\t\t\t신청</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_supportList.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">지원 내역</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a\r\n");
          out.write("\t\t\t\t\t\thref=\"project_ing.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">진행중인 프로젝트</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_end.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">완료한 프로젝트</a></li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t</nav>\r\n");
          out.write("\t<br>\r\n");
          out.write("\t<br>\r\n");
          out.write("\t<br>\r\n");
          out.write("<script>\r\n");
          out.write("  function signOut() {\r\n");
          out.write("    var auth2 = gapi.auth2.getAuthInstance();\r\n");
          out.write("    auth2.signOut().then(function () {\r\n");
          out.write("      console.log('User signed out.');\r\n");
          out.write("    });\r\n");
          out.write("  }\r\n");
          out.write("</script>\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /User_InfoUpdate.jsp(11,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '클라이언트' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write("\n");
          out.write("<html>\n");
          out.write("<head>\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
          out.write("<title>Puding</title>\n");
          out.write("\n");
          out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\n");
          out.write("<link rel=\"stylesheet\"\n");
          out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\n");
          out.write("<script\n");
          out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
          out.write("<script\n");
          out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\n");
          out.write(" <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n");
          out.write("\t<!-- 구글로그인api -->\n");
          out.write("<script src=\"https://apis.google.com/js/platform.js\" async defer></script>\n");
          out.write("<meta name=\"google-signin-scope\" content=\"profile email\">\n");
          out.write("<meta name=\"google-signin-client_id\" content=\"194507075586-fqdh9s1af0jq81cq27hqe5m9fim0692t.apps.googleusercontent.com\">\n");
          out.write("\t\n");
          out.write("<style type=\"text/css\">\n");
          out.write("#ho:hover {\n");
          out.write("\tposition: relative;\n");
          out.write("\ttop: calc(100% - 0.125rem);\n");
          out.write("\tborder-bottom: 4px solid #FFA7A7;\n");
          out.write("\tleft: 50%;\n");
          out.write("\tright: 50%;\n");
          out.write("\ttransition: all 0.5s ease;\n");
          out.write("\tleft: 0;\n");
          out.write("\tright: 0;\n");
          out.write("\ttransition: all 0.5s ease;\n");
          out.write("}\n");
          out.write("</style>\n");
          out.write("\n");
          out.write("</head>\n");
          out.write("<body>\n");
          out.write("\n");
          out.write("   <nav\n");
          out.write("      class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\n");
          out.write("      id=\"sectionsNav\">\n");
          out.write("      <div class=\"container\">\n");
          out.write("         <div class=\"navbar-translate\">\n");
          out.write("            <!-- 상단 메뉴바 -->\n");
          out.write("            <a href=\"main.do\"><img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:100px;\"/></a>\n");
          out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
          out.write("               aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
          out.write("               <span class=\"sr-only\">Toggle navigation</span> \n");
          out.write("               <span class=\"navbar-toggler-icon\"></span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span>\n");
          out.write("            </button>\n");
          out.write("         </div>\n");
          out.write("         <div class=\"collapse navbar-collapse\">\n");
          out.write("            <ul class=\"navbar-nav\">\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"client_mypage.do\" class=\"nav-link\">나의\n");
          out.write("\t\t\t\t\t\t\t푸딩</a></li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\">\n");
          out.write("\t\t\t\t\t\t<a href=\"project_insert.do\" class=\"nav-link\" style=\"color: white\">프로젝트 등록</a>\n");
          out.write("\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_list.do?page=1\"\n");
          out.write("\t\t\t\t\t\tclass=\"nav-link\" style=\"color: white\">프로젝트 찾기</a></li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a\n");
          out.write("\t\t\t\t\t\thref=\"partner_list.do\" class=\"nav-link\"\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\">파트너스 목록</a></li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"question.do\" class=\"nav-link\"\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\">이용 방법</a></li>\n");
          out.write("\t\t\t\t</ul>\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\">\n");
          out.write("\t\t\t\t\t<a href=\"message_re.do?page=1\" class=\"btn btn-rose btn-raised btn-fab btn-round\"> <i\n");
          out.write("\t\t\t\t\t\tclass=\"material-icons\">email</i></a> \n");
          out.write("\t\t\t\t\t<!-- <a class=\"btn btn-rose btn-raised btn-fab btn-round\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a> -->\n");
          out.write("\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"logOut.do\" class=\"nav-link\"\n");
          out.write("\t\t\t\t\t\tstyle=\"color: white\" onclick=\"signOut();\">Logout</a></li>\n");
          out.write("\t\t\t\t\t\t\n");
          out.write("\t\t\t\t</ul>\n");
          out.write("\t\t\t</div>\n");
          out.write("\t\t</div>\n");
          out.write("\t</nav>\n");
          out.write("\n");
          out.write("\t<nav class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\" id=\"sectionsNav\"\n");
          out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\n");
          out.write("   <nav\n");
          out.write("      class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\n");
          out.write("      id=\"sectionsNav\"\n");
          out.write("      style=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\n");
          out.write("      <div class=\"container\">\n");
          out.write("         <div class=\"navbar-translate\" style=\"width: 100px;\">\n");
          out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
          out.write("               aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
          out.write("               <span class=\"sr-only\">Toggle navigation</span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span> <span\n");
          out.write("                  class=\"navbar-toggler-icon\"></span>\n");
          out.write("            </button>\n");
          out.write("         </div>\n");
          out.write("\n");
          out.write("         <div class=\"collapse navbar-collapse\">\n");
          out.write("            <ul class=\"navbar-nav\" style=\"color:black;\">\n");
          out.write("               <li class=\"nav-item\"><a href=\"project_inspectionList.do?user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" \n");
          out.write("               class=\"nav-link\" id=\"ho\" style=\"padding-top: 17px;\">검수중인 프로젝트</a></li>\n");
          out.write("               <li class=\"nav-item\"><a href=\"project_recruitmentList.do?user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link\" id=\"ho\"\n");
          out.write("                  style=\"padding-top: 17px;\">지원자 모집 중</a></li>\n");
          out.write("                <li class=\"nav-item\"><a href=\"project_ing.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link\" id=\"ho\"\n");
          out.write("                  style=\"padding-top: 17px;\">진행중인 프로젝트</a></li>\n");
          out.write("                  <li class=\"nav-item\"><a href=\"project_end.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link\" id=\"ho\"\n");
          out.write("                  style=\"padding-top: 17px;\">완료한 프로젝트</a></li>\n");
          out.write("                  <li class=\"nav-item\"><a href=\"user_typeUpdate.do\" class=\"nav-link\" id=\"ho\"\n");
          out.write("                  style=\"padding-top: 17px;\">계정 유형 변경 신청</a></li>\n");
          out.write("            </ul>\n");
          out.write("         </div>\n");
          out.write("         </div>\n");
          out.write("         </nav>\n");
          out.write("         \n");
          out.write("   </nav>\n");
          out.write("   <br><br><br>\n");
          out.write("\n");
          out.write("<script>\n");
          out.write("  function signOut() {\n");
          out.write("    var auth2 = gapi.auth2.getAuthInstance();\n");
          out.write("    auth2.signOut().then(function () {\n");
          out.write("      console.log('User signed out.');\n");
          out.write("    });\n");
          out.write("  }\n");
          out.write("</script>\n");
          out.write("</body>\n");
          out.write("</html>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /User_InfoUpdate.jsp(14,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '투자자' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write("\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("<title>Puding</title>\r\n");
          out.write("<link href=\"resources/assets/css/topbar_kit.css\" rel=\"stylesheet\" />\r\n");
          out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
          out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
          out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
          out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
          out.write("  <!-- 구글로그인api -->\r\n");
          out.write("<script src=\"https://apis.google.com/js/platform.js\" async defer></script>\r\n");
          out.write("<meta name=\"google-signin-scope\" content=\"profile email\">\r\n");
          out.write("<meta name=\"google-signin-client_id\" content=\"194507075586-fqdh9s1af0jq81cq27hqe5m9fim0692t.apps.googleusercontent.com\">\r\n");
          out.write("  \r\n");
          out.write("\r\n");
          out.write("<style type=\"text/css\">\r\n");
          out.write("\r\n");
          out.write("#ho:hover {\r\n");
          out.write("\tposition: relative;\r\n");
          out.write("\ttop: calc(100% - 0.125rem);\r\n");
          out.write("\tborder-bottom: 4px solid #FFA7A7;\r\n");
          out.write("\tleft: 50%;\r\n");
          out.write("\tright: 50%;\r\n");
          out.write("\ttransition: all 0.5s ease;\r\n");
          out.write(" \tleft: 0;\r\n");
          out.write("  \tright: 0;\r\n");
          out.write(" \ttransition: all 0.5s ease;\r\n");
          out.write("}\r\n");
          out.write("</style>\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("\t<nav\r\n");
          out.write("\t\tclass=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg\"\r\n");
          out.write("\t\tid=\"sectionsNav\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"navbar-translate\">\r\n");
          out.write("\t\t\t\t<a href=\"main.do\"><img src=\"resources/assets/img/main_Icon_white.png\" id=\"main_logo\" style=\"width:100px;\"/></a>\r\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\" >\r\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\r\n");
          out.write("\t\t\t\t</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\">\r\n");
          out.write("\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"project_list.do?page=1\" class=\"nav-link\">프로젝트 찾기</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"partner_list.do\" class=\"nav-link\">파트너스 목록</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("                  <li class=\"nav-item\">\r\n");
          out.write("                    <a href=\"question.do\" class=\"nav-link\">이용 방법</a>\r\n");
          out.write("                  </li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\" style=\"float: right;\">\r\n");
          out.write("\t\t\t\t\t\t<a href=\"message_re.do?page=1\" class=\"btn btn-rose btn-raised btn-fab btn-round\">\r\n");
          out.write("\t\t\t\t\t\t\t <i class=\"material-icons\">email</i>\r\n");
          out.write("\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#pablo\" class=\"nav-link\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
          out.write("\t\t\t\t\t\t<a href=\"logOut.do\" class=\"nav-link\"style=\"color: white\" onclick=\"signOut();\">Logout</a>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</nav>\r\n");
          out.write("\r\n");
          out.write("\t<nav\r\n");
          out.write("\t\tclass=\"navbar navbar-transparent fixed-top navbar-expand-lg\"\r\n");
          out.write("\t\tid=\"sectionsNav2\"\r\n");
          out.write("\t\tstyle=\"background-color: #D5D5D5; margin-top: 70px; height: 55px;\">\r\n");
          out.write("\t\t<div class=\"container\">\r\n");
          out.write("\t\t\t<div class=\"navbar-translate\" style=\"width: 100px;\">\r\n");
          out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
          out.write("\t\t\t\t\taria-expanded=\"false\" data-target=\"#investor_topbar\">\r\n");
          out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span> <span\r\n");
          out.write("\t\t\t\t\t\tclass=\"navbar-toggler-icon\"></span>\r\n");
          out.write("\t\t\t\t</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"investor_topbar\">\r\n");
          out.write("\t\t\t\t<ul class=\"navbar-nav\" style=\"color:black;\">\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"user_coin.do?page=1&user_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"nav-link\" id=\"ho\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">코인 관리</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"user_typeUpdate.do\" class=\"nav-link\" id=\"ho\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">계정 유형 변경 신청</a></li>\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"project_fundinglist.do\" class=\"nav-link\" id=\"ho\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"padding-top: 17px;\">투자한 프로젝트</a></li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\n");
          out.write("\t</nav>\r\n");
          out.write("\t<br>\r\n");
          out.write("\t<br>\r\n");
          out.write("\t<br>\r\n");
          out.write("<script>\r\n");
          out.write("  function signOut() {\r\n");
          out.write("    var auth2 = gapi.auth2.getAuthInstance();\r\n");
          out.write("    auth2.signOut().then(function () {\r\n");
          out.write("      console.log('User signed out.');\r\n");
          out.write("    });\r\n");
          out.write("  }\r\n");
          out.write("</script>\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /User_InfoUpdate.jsp(87,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '파트너스' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("<title>Insert title here</title>\r\n");
          out.write(" <link href=\"resources/assets/css/pw_change.css\" rel=\"stylesheet\">\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("\r\n");
          out.write("\t<div class=\"col-md-3\" id=\"sidebar\">\r\n");
          out.write("\t\t<b>파트너스</b>&nbsp;&nbsp; <a href=\"user_infoUpdate.do\"><b>기본정보 수정하기</b></a>\r\n");
          out.write("\t\t<hr>\r\n");
          out.write("\t\t<div class=\"user_info\">\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t<div class=\"user_info\">\r\n");
          out.write("\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t\t<hr>\r\n");
          out.write("\t\t<div class=\"col-md-12\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t<a class=\"btn btn-link2 active\" href=\"partnerReg_info.do\">파트너스 정보</a> \r\n");
          out.write("\t\t\t<a class=\"btn btn-link2 active\" href=\"partnerReg_about.do\">자기 소개</a> \r\n");
          out.write("\t\t\t<a class=\"btn btn-link2 active\" href=\"partnerReg_portfolio.do\">포트폴리오</a>\r\n");
          out.write("\t\t\t<a class=\"btn btn-link2 active\" href=\"partnerReg_technology.do\">보유 기술</a>\r\n");
          out.write("\t\t\t<a class=\"btn btn-link2 active\" href=\"partnerReg_career.do\">경력/학력/자격증</a>\r\n");
          out.write("\t\t\t<a class=\"btn btn-link2 active\" href=\"user_delete.do\">회원탈퇴</a>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/inc/partners_sidebar.jsp(20,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_img eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"resources/assets/img/남자.png\" class=\"user_img rounded-circle img-fluid\" />\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"http://localhost:8787/pf/storage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"user_img rounded-circle img-fluid\" />\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /User_InfoUpdate.jsp(90,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '클라이언트' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t");
          out.write("\r\n");
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("<title>Insert title here</title>\r\n");
          out.write(" <link href=\"resources/assets/css/pw_change.css\" rel=\"stylesheet\">\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("\r\n");
          out.write("\t<div class=\"col-md-3\" id=\"sidebar\">\r\n");
          out.write("\t\t<b>클라이언트</b>&nbsp;&nbsp; <a href=\"user_infoUpdate.do\"><b>기본정보 수정하기</b></a>\r\n");
          out.write("\t\t<hr>\r\n");
          out.write("\t\t<div class=\"user_info\">\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t<div class=\"user_info\">\r\n");
          out.write("\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t\t<hr>\r\n");
          out.write("\t\t<div class=\"col-md-12\">\r\n");
          out.write("\t\t\t<a class=\"btn btn-link2\" href=\"partnerReg_about.do\">자기소개 등록</a> \r\n");
          out.write("\t\t\t<a class=\"btn btn-link2\" href=\"user_pwUpdate.do\">비밀번호변경</a> \r\n");
          out.write("\t\t\t<a class=\"btn btn-link2\" href=\"user_typeUpdate.do\">계정 유형 변경 신청</a><br /> \r\n");
          out.write("\t\t\t<a class=\"btn btn-link2\" href=\"user_delete.do\">회원탈퇴</a>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/inc/client_sidebar.jsp(19,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_img eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"resources/assets/img/남자.png\" class=\"user_img rounded-circle img-fluid\" />\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"http://localhost:8787/pf/storage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"user_img rounded-circle img-fluid\" />\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /User_InfoUpdate.jsp(93,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.getUser_type() eq '투자자' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t");
          out.write("\r\n");
          out.write("\r\n");
          out.write("<!DOCTYPE html>\r\n");
          out.write("<html>\r\n");
          out.write("<head>\r\n");
          out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
          out.write("<title>Insert title here</title>\r\n");
          out.write(" <link href=\"resources/assets/css/pw_change.css\" rel=\"stylesheet\">\r\n");
          out.write(" <script src=\"http://code.jquery.com/jquery-1.11.3.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
          out.write("\r\n");
          out.write(" <!-- \r\n");
          out.write(" <script type=\"text/javascript\">\r\n");
          out.write(" $(function(){\r\n");
          out.write("\t  var sBtn = $(\"#clickevent\");    //  ul > li 이를 sBtn으로 칭한다. (클릭이벤트는 li에 적용 된다.)\r\n");
          out.write("\t  sBtn.click(function(){   // sBtn에 속해 있는  a 찾아 클릭 하면.\r\n");
          out.write("\t   sBtn.removeClass(\"active\");     // sBtn 속에 (active) 클래스를 삭제 한다.\r\n");
          out.write("\t   $(this).addClass(\"active\"); // 클릭한 a에 (active)클래스를 넣는다.\r\n");
          out.write("\t  })\r\n");
          out.write(" })\r\n");
          out.write("</script>\r\n");
          out.write("\r\n");
          out.write("<style type=\"text/css\">\r\n");
          out.write("a.active{\r\n");
          out.write("\r\n");
          out.write("\tbackground-color:#ccc;\r\n");
          out.write("\tcolor:white;\r\n");
          out.write("}\r\n");
          out.write("</style>\r\n");
          out.write(" \r\n");
          out.write("\r\n");
          out.write(" <script>\r\n");
          out.write("\t $(function(){\r\n");
          out.write("\t  var sBtn = $(\"div\");    //  ul > li 이를 sBtn으로 칭한다. (클릭이벤트는 li에 적용 된다.)\r\n");
          out.write("\t  sBtn.find(\"a\").click(function(){   // sBtn에 속해 있는  a 찾아 클릭 하면.\r\n");
          out.write("\t   sBtn.removeClass(\"active\");     // sBtn 속에 (active) 클래스를 삭제 한다.\r\n");
          out.write("\t   $(this).parent().addClass(\"active\"); // 클릭한 a에 (active)클래스를 넣는다.\r\n");
          out.write("\t  })\r\n");
          out.write("\t })\r\n");
          out.write("</script>\r\n");
          out.write("-->\r\n");
          out.write("</head>\r\n");
          out.write("<body>\r\n");
          out.write("\r\n");
          out.write("\t<div class=\"col-md-3\" id=\"sidebar\">\r\n");
          out.write("\t\t<b>투자자</b>&nbsp;&nbsp; <a href=\"user_infoUpdate.do\"><b>기본정보 수정하기</b></a>\r\n");
          out.write("\t\t<hr>\r\n");
          out.write("\t\t<div class=\"user_info\">\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fif_005f5, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t<div class=\"user_info\">\r\n");
          out.write("\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t\t<hr>\r\n");
          out.write("\t\t<div class=\"col-md-12\">\r\n");
          out.write("\t\t\t<a id=\"clickevent\" class=\"btn btn-link2 active\" href=\"user_coin.do\">코인 조회/결제</a> \r\n");
          out.write("\t\t\t<a id=\"clickevent\" class=\"btn btn-link2\" href=\"user_delete.do\">회원탈퇴</a>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("</body>\r\n");
          out.write("</html>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/inc/investor_sidebar.jsp(50,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_img eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"resources/assets/img/남자.png\" class=\"user_img rounded-circle img-fluid\" />\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"http://localhost:8787/pf/storage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userdto.user_img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"user_img rounded-circle img-fluid\" />\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }
}
